name: Publish a Python distribution to PyPI
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}